name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Build App
      run: xcodebuild -project "Recipe-App.xcodeproj" -scheme "Recipe-App" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO


 
